spring:
  jpa:
    properties:
      hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 25
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgresDB}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
